# Generated by Django 4.1 on 2022-08-31 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0001_added_order_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='orderproduct',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='orderproduct',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='shippingdetails',
            old_name='order_id',
            new_name='order',
        ),
    ]
