# Generated by Django 4.1 on 2022-09-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0005_updated_order_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='o_placed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
