# Generated by Django 4.1 on 2022-08-29 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_store', '0003_alter_category_c_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='c_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
