# Generated by Django 4.1 on 2022-08-30 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_store', '0004_alter_category_c_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='c_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
