# Generated by Django 4.1 on 2022-08-30 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_store', '0005_alter_category_c_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-id']},
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=200)),
                ('p_code', models.CharField(max_length=50)),
                ('p_description', models.CharField(max_length=50)),
                ('p_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('p_stock', models.PositiveIntegerField()),
                ('p_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('p_uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('p_updated_date', models.DateTimeField(auto_now=True)),
                ('p_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_store.category')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
