# Generated by Django 4.1 on 2022-08-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_store', '0006_Added_Product_Model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='p_category_id',
            new_name='p_category',
        ),
        migrations.AlterField(
            model_name='product',
            name='p_code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
