# Generated by Django 4.1 on 2022-08-30 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_store', '0007_Added_Product_Model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='p_category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='manage_store.category'),
        ),
    ]
